Add commands for submission.

diff --git a/bin/imosh b/bin/imosh
--- a/bin/imosh
+++ b/bin/imosh
@@ -3,7 +3,7 @@
 #
 # For more details, see https://github.com/imos/imosh
 
-IMOSH_VERSION='2015-02-03 22:43:00 +0900 (ebe03c4)'
+IMOSH_VERSION='2015-07-31 06:08:01 +0900 (c50e1f8)'
 
 # Enables error checking if imosh is called in a script.
 if ! shopt login_shell >/dev/null; then
@@ -42,6 +42,12 @@ func::array() {
 # Usage:
 #     // 1. Command form.
 #     bool sub::array_is_empty(string[]* variable)
+#
+# Example:
+#     array=()
+#     if sub::array_is_empty array; then
+#       echo 'array is empty.'
+#     fi
 sub::array_is_empty() {
   if [ "$#" -eq 1 ]; then
     if eval "[ \"\${#${1}[*]}\" -eq 0 ]"; then return 0; fi
@@ -60,6 +66,13 @@ sub::array_is_empty() {
 #     void func::array_keys(string[]* output, string[]* input)
 #     // 2. Command form.
 #     void sub::array_keys(string[]* input) > output
+#
+# Examples:
+#     array=([0]=abc [2]=def)
+#     EXPECT_EQ '0,2' "$(IFS=, sub::array_keys array)"
+#     func::array_keys result array
+#     EXPECT_EQ '0' "${result[0]}"
+#     EXPECT_EQ '2' "${result[1]}"
 func::array_keys() {
   if [ "$#" -eq 2 ]; then
     if eval "[ \"\${#${2}[*]}\" -eq 0 ]"; then
@@ -129,6 +142,7 @@ func::array_map() {
     local __array_map_variable="${1}"; shift
     local __array_map_type="${1}"; shift
     local __array_map_callback="${1}"; shift
+    CHECK sub::function_exists "${__array_map_callback}"
 
     local __array_map_keys=()
     local __array_map_key=''
@@ -261,6 +275,10 @@ stream::array_unique() {
 #     void func::array_values(string[]* output, string[]* input)
 #     // 2. Command form.
 #     void sub::array_values(string[]* input) > output
+#
+# Examples:
+#     array=(foo bar)
+#     EXPECT_EQ 'foo,bar' "$(IFS=, sub::array_values array)"
 func::array_values() {
   if [ "$#" -eq 2 ]; then
     if sub::array_is_empty "${2}"; then
@@ -303,6 +321,30 @@ func::count() {
 sub::count() {
   if [ "$#" -eq 1 ]; then
     eval "sub::println \"\${#${1}[*]}\""
+  else
+    eval "${IMOSH_WRONG_NUMBER_OF_ARGUMENTS}"
+  fi
+}
+
+# in_array -- Checks if a value exists in an array.
+#
+# Searches haystack for needle.
+#
+# Usage:
+#     // 1. Command form.
+#     bool sub::in_array(string needle, string[]* haystack)
+sub::in_array() {
+  if [ "$#" -eq 2 ]; then
+    if sub::array_is_empty "${2}"; then
+      return 1
+    fi
+    eval "
+        for value in \"\${${2}[@]}\"; do
+          if [ \"\${value}\" == \"\${1}\" ]; then
+            return
+          fi
+        done"
+    return 1
   else
     eval "${IMOSH_WRONG_NUMBER_OF_ARGUMENTS}"
   fi
@@ -605,7 +647,7 @@ func::strtotime() {
     # 2006:01:02 15:04:05 (EXIF)
     # 2006-01-02T15:04:05
     if sub::ereg_match \
-        '^([0-9]{4})[-/:]?([0-9]{2})[-/:]?([0-9]{2})[ T]?([0-9]{2})[:\-]?([0-9]{2})[:\-]?([0-9]{2}) *([A-Za-z0-9\-\+ /]+)?$' \
+        '^([0-9]{4})[-/:]?([0-9]{2})[-/:]?([0-9]{2})[ T]?([0-9]{2})[:\-]?([0-9]{2})[:\-]?([0-9]{2}) *([A-Za-z0-9\-\+: /]+)?$' \
         "${2}" __func_strtotime_match; then
       __func_strtotime_text+="${__func_strtotime_match[1]}"
       __func_strtotime_text+="-${__func_strtotime_match[2]}"
@@ -617,7 +659,7 @@ func::strtotime() {
       __func_strtotime_format='%Y-%m-%d %H:%M:%S'
     # Mon, 02 Jan 2006 15:04:05 GMT (HTTP format)
     elif sub::ereg_match \
-        '^([A-Z][a-z]+, +)?([0-9]+)[/ \-]+([A-Z][a-z][a-z])[/ \-]+([0-9]{2}|[0-9]{4})[ :T]([0-9]{2})[:\-]([0-9]{2})[:\-]([0-9]{2}) *([A-Z][A-Za-z0-9\-\+ /]+)?([\-\+][0-9]{4})?$' \
+        '^([A-Z][a-z]+, +)?([0-9]+)[/ \-]+([A-Z][a-z][a-z])[/ \-]+([0-9]{2}|[0-9]{4})[ :T]([0-9]{2})[:\-]([0-9]{2})[:\-]([0-9]{2}) *([A-Za-z0-9\-\+: /]+)?$' \
         "${2}" __func_strtotime_match; then
       if [ "${#__func_strtotime_match[4]}" -eq 2 ]; then
         if [ "${__func_strtotime_match[4]}" -lt 70 ]; then
@@ -634,13 +676,14 @@ func::strtotime() {
           "${__func_strtotime_match[6]}" \
           "${__func_strtotime_match[7]}"
       __func_strtotime_timezone+="${__func_strtotime_match[8]}"
-      __func_strtotime_timezone+="${__func_strtotime_match[9]}"
       __func_strtotime_format='%d %b %Y %H:%M:%S'
     else
       LOG ERROR "Unkown date format: ${2}"
       return 1
     fi
     case "${__func_strtotime_timezone}" in
+      '-'*':'*|'+'*':'*)
+            func::str_replace __func_strtotime_timezone ':' '';;
       'Z')   __func_strtotime_timezone='+0000';;
       'JST') __func_strtotime_timezone='+0900';;
     esac
@@ -698,7 +741,8 @@ __func::strtotime() {
 #     void sub::time() > output
 func::time() {
   if [ "$#" -eq 1 ]; then
-    sub::let "${1}" "$(date +'%s')"
+    func::exec "${1}" date +'%s'
+    func::rtrim "${1}"
   else
     eval "${IMOSH_WRONG_NUMBER_OF_ARGUMENTS}"
   fi
@@ -883,6 +927,27 @@ sub::tmpfile() {
     local tmpfile=''
     func::tmpfile tmpfile
     sub::println "${tmpfile}"
+  else
+    eval "${IMOSH_WRONG_NUMBER_OF_ARGUMENTS}"
+  fi
+}
+
+# function_exists -- Returns true iff the given function has been defined.
+#
+# Checks the list of defined functions, both built-in (internal) and
+# user-defined, for function_name.
+#
+# Usage:
+#     // 1. Command form.
+#     bool sub::function_exists(string function_name)
+#
+# Examples:
+#     EXPECT_TRUE sub::function_exists func::array
+sub::function_exists() {
+  if [ "$#" -eq 1 ]; then
+    if ! type -t "${1}" >'/dev/null'; then
+      return 1
+    fi
   else
     eval "${IMOSH_WRONG_NUMBER_OF_ARGUMENTS}"
   fi
@@ -1966,6 +2031,38 @@ stream::md5() {
   fi
 }
 
+# md5 -- Calculates the MD5 hash of a given file.
+#
+# Usage:
+#     // 1. Function form.
+#     void func::md5_file(string* variable, string filename)
+#     // 2. Command form.
+#     void sub::md5_file(string filename, bool binary = false) > hash
+func::md5_file() {
+  if [ "$#" -eq 2 ]; then
+    local __md5_file_variable="${1}"
+    shift
+    func::exec "${__md5_file_variable}" sub::md5_file "$@"
+    func::rtrim "${__md5_file_variable}"
+  else
+    eval "${IMOSH_WRONG_NUMBER_OF_ARGUMENTS}"
+  fi
+}
+
+sub::md5_file() {
+  if [ "$#" -eq 2 ]; then
+    if [ "${2}" -eq 0 ]; then
+      sub::md5_file "${1}" 1 | stream::bin2hex
+    else
+      openssl md5 -binary "${1}"
+    fi
+  elif [ "$#" -eq 1 ]; then
+    sub::md5_file "$@" 0
+  else
+    eval "${IMOSH_WRONG_NUMBER_OF_ARGUMENTS}"
+  fi
+}
+
 # ord -- Gets a character's ASCII code.
 #
 # Sets ASCII value of character to variable.
@@ -2078,6 +2175,50 @@ stream::rtrim() {
       func::rtrim LINE
       sub::print "${LINE}${NEWLINE}"
     done
+  else
+    eval "${IMOSH_WRONG_NUMBER_OF_ARGUMENTS}"
+  fi
+}
+
+# sha1 -- Calculates a MD5 hash.
+#
+# Usage:
+#     // 1. Function form.
+#     void func::sha1(string* variable, string data)
+#     // 2. Command form.
+#     void sub::sha1(string data, bool binary = false) > hash
+#     // 3. Stream form.
+#     void stream::sha1(bool binary = false) < input > hash
+func::sha1() {
+  if [ "$#" -eq 2 ]; then
+    local __sha1_file=''
+    func::tmpfile __sha1_file
+    sub::sha1 "${2}" 0 > "${__sha1_file}"
+    func::file_get_contents "${1}" "${__sha1_file}"
+  else
+    eval "${IMOSH_WRONG_NUMBER_OF_ARGUMENTS}"
+  fi
+}
+
+sub::sha1() {
+  if [ "$#" -eq 2 ]; then
+    sub::print "${1}" | stream::sha1 "${2}"
+  elif [ "$#" -eq 1 ]; then
+    sub::sha1 "$@" 0
+  else
+    eval "${IMOSH_WRONG_NUMBER_OF_ARGUMENTS}"
+  fi
+}
+
+stream::sha1() {
+  if [ "$#" -eq 1 ]; then
+    if [ "${1}" -eq 0 ]; then
+      stream::sha1 1 | stream::bin2hex
+    else
+      openssl sha1 -binary
+    fi
+  elif [ "$#" -eq 0 ]; then
+    stream::sha1 0
   else
     eval "${IMOSH_WRONG_NUMBER_OF_ARGUMENTS}"
   fi
@@ -2891,6 +3032,7 @@ func::cast() {
         func::array_values "${1}" __cast_values
         ;;
       'INT')     func::intval "${1}" || return "$?";;
+      'ENUM')    func::enumval "${1}" || return "$?";;
       'FLOAT')   func::floatval "${1}" || return "$?";;
       'STRING')  func::strval "${1}" || return "$?";;
       'BOOL')    func::boolval "${1}" || return "$?";;
@@ -2905,6 +3047,42 @@ func::cast() {
 func::cast_or_die() {
   if ! func::cast "${@}"; then
     IFS=' ' eval 'LOG FATAL "Type mismatch: ${*}"'
+  fi
+}
+
+# enumval -- Casts a variable as an enum value.
+#
+# Casts variable into enum type.  If it fails, returns 1.
+#
+# Usage:
+#     // 1-a. Function from.
+#     bool func::enumval(string* output, string input)
+#     // 1-b. Inplace function form.
+#     bool func::enumval(string* variable)
+#     // 2. Command form.
+#     bool sub::enumval(string input) > output
+func::enumval() {
+  if [ "$#" -eq 2 ]; then
+    if sub::in_array "${2}" __imosh_enum_values; then
+      func::let "${1}" "${2}"
+    else
+      func::let "${1}" "${__imosh_enum_values[0]}"
+      return 1
+    fi
+  elif [ "$#" -eq 1 ]; then
+    eval "func::enumval \"\${1}\" \"\${${1}}\" || return \"\$?\""
+  else
+    eval "${IMOSH_WRONG_NUMBER_OF_ARGUMENTS}"
+  fi
+}
+
+sub::enumval() {
+  if [ "$#" -eq 1 ]; then
+    local __enumval_value="${1}"
+    func::enumval __enumval_value || return "$?"
+    sub::println "${__enumval_value}"
+  else
+    eval "${IMOSH_WRONG_NUMBER_OF_ARGUMENTS}"
   fi
 }
 
@@ -2992,8 +3170,7 @@ sub::intval() {
 #   false for them in BASH 4.
 func::isset() {
   if [ "$#" -eq 2 ]; then
-    eval "local __isset_state=\"\${${2}+set}\""
-    if [ "${__isset_state}" = 'set' ]; then
+    if declare -p "${2}" &>/dev/null; then
       func::let "${1}" 1
     else
       func::let "${1}" 0
@@ -3142,6 +3319,11 @@ imosh::internal::parse_args() {
         # TODO(imos): Support delimiter.
         func::explode arg_value ',' "${arg_value}"
       fi
+      if [ "${single_type}" = 'ENUM' ]; then
+        local __imosh_enum_values=()
+        func::array_values \
+            __imosh_enum_values "__IMOSH_FLAGS_ENUM_VALUES_${arg_name}"
+      fi
       CHECK --message="FLAGS_${arg_name} is invalid: ${arg_value}" \
             func::cast arg_value "${single_type}"
       local is_default=0
@@ -3188,6 +3370,9 @@ imosh::internal::flag_type() {
 imosh::internal::define_flag() {
   local type="$1"; shift
 
+  if [ "${type}" == 'ENUM' -o "${type}" == 'MULTIENUM' ]; then
+    local ARGS_values=''
+  fi
   local ARGS_alias='' ARGS_alias_flag=0 ARGS_group='main'
   eval "${IMOSH_PARSE_ARGUMENTS}"
 
@@ -3200,6 +3385,15 @@ imosh::internal::define_flag() {
   local description="$*"
   local group="${ARGS_group}"
   func::strtoupper group
+
+  if [ "${type}" == 'ENUM' -o "${type}" == 'MULTIENUM' ]; then
+    local __imosh_enum_values=()
+    if [ "${ARGS_values}" == '' ]; then
+      LOG FATAL "No enum values are specified for ${name}."
+    fi
+    func::explode __imosh_enum_values ',' "${ARGS_values}"
+    func::array_values "__IMOSH_FLAGS_ENUM_VALUES_${name}" __imosh_enum_values
+  fi
 
   # Change the default value based on its corresponding environment variable.
   if sub::isset "IMOSH_FLAGS_${name}"; then
@@ -3259,15 +3453,18 @@ imosh::internal::define_flag() {
   fi
 }
 
-DEFINE_string() { imosh::internal::define_flag STRING "$@"; }
-DEFINE_int() { imosh::internal::define_flag INT "$@"; }
 DEFINE_bool() { imosh::internal::define_flag BOOL "$@"; }
 DEFINE_double() { imosh::internal::define_flag DOUBLE "$@"; }
-DEFINE_multistring() { imosh::internal::define_flag MULTISTRING "$@"; }
-DEFINE_multiint() { imosh::internal::define_flag MULTIINT "$@"; }
+DEFINE_enum() { imosh::internal::define_flag ENUM "$@"; }
+DEFINE_int() { imosh::internal::define_flag INT "$@"; }
+DEFINE_list() { imosh::internal::define_flag LIST "$@"; }
+DEFINE_string() { imosh::internal::define_flag STRING "$@"; }
+
 DEFINE_multibool() { imosh::internal::define_flag MULTIBOOL "$@"; }
 DEFINE_multidouble() { imosh::internal::define_flag MULTIDOUBLE "$@"; }
-DEFINE_list() { imosh::internal::define_flag LIST "$@"; }
+DEFINE_multienum() { imosh::internal::define_flag MULTIENUM "$@"; }
+DEFINE_multiint() { imosh::internal::define_flag MULTIINT "$@"; }
+DEFINE_multistring() { imosh::internal::define_flag MULTISTRING "$@"; }
 
 imosh::internal::get_main_script() {
   local depth="${#BASH_SOURCE[*]}"
