Update play_icfp2015.

diff --git a/play_icfp2015 b/play_icfp2015
--- a/play_icfp2015
+++ b/play_icfp2015
@@ -1,3 +1,7 @@
 #!/bin/bash
 
-"$(dirname "${BASH_SOURCE}")/bin/play_icfp2015" "$@"
+if [ "$(pwd)" != "$(cd "$(dirname "${BASH_SOURCE}")"; pwd)" ]; then
+  echo 'play_icfp2015 command cannot be run outside of the directory.' >&2
+  exit 1
+fi
+php "$(dirname "${BASH_SOURCE}")/play_icfp2015.php" "$@"
